name = "imm-verifier-ptj"
compatibility_date = "2024-09-23"
pages_build_output_dir = "."

[[d1_databases]]
binding = "DB"
database_name = "imm-verifier-auth"
database_id = "5c9cd585-b83c-4e0c-8560-d61df72a79b6"
